# Generated by Django 3.1 on 2020-08-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Machinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mach_status', models.SmallIntegerField(choices=[(0, '未借出'), (1, '已借出'), (2, '未借出，故障')], default='0', verbose_name='设备状态')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='设备名称')),
                ('sn', models.CharField(max_length=128, verbose_name='型号')),
                ('mach_num', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备编号')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('user', models.CharField(blank=True, max_length=128, null=True, verbose_name='领用人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('out_time', models.DateTimeField(blank=True, verbose_name='借出日期')),
                ('djuser', models.ForeignKey(blank=True, max_length=1024, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysmg.user', verbose_name='录入人')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息表',
                'ordering': ['-create_time'],
            },
        ),
    ]
