# Generated by Django 3.1 on 2020-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinfo',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='machinfo',
            name='out_time',
            field=models.DateField(blank=True, null=True, verbose_name='借出日期'),
        ),
        migrations.AlterField(
            model_name='machinfo',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=32),
        ),
    ]
