# Generated by Django 3.1 on 2020-08-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0002_auto_20200813_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinfo',
            name='out_time',
            field=models.DateField(blank=True, default='0000-00-00', null=True, verbose_name='借出日期'),
        ),
    ]
