# Generated by Django 3.1 on 2020-08-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0003_auto_20200813_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinfo',
            name='out_time',
            field=models.DateField(blank=True, null=True, verbose_name='借出日期'),
        ),
        migrations.CreateModel(
            name='Operationlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationtype', models.IntegerField(choices=[(1, '新增设备'), (2, '编辑设备'), (3, '删除设备'), (4, '登陆系统')])),
                ('createtime', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, max_length=1024, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysmg.user', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '用户日志',
                'verbose_name_plural': '用户日志',
                'ordering': ['-createtime'],
            },
        ),
    ]
