# Generated by Django 3.1 on 2020-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0004_auto_20200813_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
