# Generated by Django 3.1 on 2020-08-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0005_auto_20200813_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlog',
            name='description',
        ),
    ]
