# Generated by Django 3.1 on 2020-08-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0008_operationlog_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='operationtype',
            field=models.IntegerField(choices=[(1, '新增设备'), (2, '编辑设备'), (3, '删除设备'), (4, '登陆系统')], verbose_name='操作类型'),
        ),
    ]
