# Generated by Django 3.1 on 2020-08-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0012_auto_20200814_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinfo',
            old_name='out_time',
            new_name='outtime',
        ),
    ]
