# Generated by Django 3.1 on 2020-08-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0013_auto_20200814_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='machinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
