# Generated by Django 3.1 on 2020-08-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0014_auto_20200814_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinfo',
            name='outtime',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='借出日期'),
        ),
    ]
