# Generated by Django 3.1 on 2020-08-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0016_user_admintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='.', verbose_name='照片'),
        ),
    ]
