# Generated by Django 3.1 on 2020-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0018_auto_20200818_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mach/', verbose_name='照片'),
        ),
    ]
