# Generated by Django 3.1 on 2020-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0021_auto_20200818_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
