# Generated by Django 3.1 on 2020-08-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmg', '0023_auto_20200818_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
